// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: characters.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNewCharacter = `-- name: CreateNewCharacter :one
INSERT INTO characters (id, health, mana, stamina, strength, job, name, skill_id, weapon_id, icon) 
VALUES (
	get_random_uuid(),
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9
)
RETURNING id, health, mana, stamina, strength, job, name, skill_id, weapon_id, icon
`

type CreateNewCharacterParams struct {
	Health   sql.NullInt32
	Mana     sql.NullInt32
	Stamina  sql.NullInt32
	Strength sql.NullInt32
	Job      sql.NullInt32
	Name     sql.NullString
	SkillID  uuid.NullUUID
	WeaponID uuid.NullUUID
	Icon     sql.NullString
}

func (q *Queries) CreateNewCharacter(ctx context.Context, arg CreateNewCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createNewCharacter,
		arg.Health,
		arg.Mana,
		arg.Stamina,
		arg.Strength,
		arg.Job,
		arg.Name,
		arg.SkillID,
		arg.WeaponID,
		arg.Icon,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Health,
		&i.Mana,
		&i.Stamina,
		&i.Strength,
		&i.Job,
		&i.Name,
		&i.SkillID,
		&i.WeaponID,
		&i.Icon,
	)
	return i, err
}

const deleteAllCharacters = `-- name: DeleteAllCharacters :exec
DELETE FROM characters
`

func (q *Queries) DeleteAllCharacters(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCharacters)
	return err
}

const deleteOneCharacter = `-- name: DeleteOneCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteOneCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOneCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, health, mana, stamina, strength, job, name, skill_id, weapon_id, icon FROM CHARACTERS WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Health,
		&i.Mana,
		&i.Stamina,
		&i.Strength,
		&i.Job,
		&i.Name,
		&i.SkillID,
		&i.WeaponID,
		&i.Icon,
	)
	return i, err
}
