// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Character struct {
	ID       uuid.UUID
	Health   sql.NullInt32
	Mana     sql.NullInt32
	Stamina  sql.NullInt32
	Strength sql.NullInt32
	Job      sql.NullInt32
	Name     sql.NullString
	SkillID  uuid.NullUUID
	WeaponID uuid.NullUUID
	Icon     sql.NullString
}

type Skill struct {
	ID          uuid.UUID
	Coin        sql.NullString
	AmountToPay sql.NullInt32
	Damage      sql.NullInt32
	Role        sql.NullInt32
	Reach       sql.NullInt32
	Name        sql.NullString
	Description sql.NullString
}

type Terrain struct {
	ID     int32
	Matrix [][]int32
}

type Weapon struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
	Damage      sql.NullInt32
	Reach       sql.NullInt32
	Role        sql.NullInt32
}
